app:
  image: 'firstandthird/node:10.10-dev'
  volumes:
    - '.:/home/app/src'
    - './example:/home/app/src/templates'
  environment:
    PORT: 8081
    VIRTUAL_HOST: 'micromail.*'
    PAGEDATA_HOST:
    PAGEDATA_KEY:
    PAGEDATA_STATUS: 'draft'
    MICROMAIL_API_KEY: 'abcd'
    MICRO_METRICS_HOST:
    SMTP_HOST: 'mailhog'
    SMTP_PORT: 1025
    FORCE_COLOR: 1
  ports:
    - '80:8081'
  links:
    - 'mailhog'
mailhog:
  image: 'mailhog/mailhog'
  hostname: 'mailhog'
  ports:
    - '8025:8025'
    - '1025:1025'
