proxy:
  image: traefik
  command: --web --docker --logLevel=DEBUG
  ports:
    - "80:80"
    - "8080:8080"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /dev/null:/traefik.toml

app:
  image: 'firstandthird/node:10.10-dev'
  hostname: 'mail'
  volumes:
    - '.:/home/app/src'
    - './example:/home/app/src/templates'
  environment:
    NODE_ENV: 'dev'
    PORT: 8081
    PAGEDATA_HOST:
    PAGEDATA_KEY:
    PAGEDATA_STATUS: 'draft'
    MICROMAIL_API_KEY: 'abcd'
    MICRO_METRICS_HOST:
    SMTP_HOST: 'mailhog'
    SMTP_PORT: 1025
    FORCE_COLOR: 1
  ports:
    - '8081'
  links:
    - 'proxy:proxy'
    - 'mailhog'
  labels:
    - "traefik.frontend.rule=PathPrefix:/"
    - "traefik.port=8081"
mailhog:
  image: 'mailhog/mailhog'
  hostname: 'mailhog'
  ports:
    - '8025:8025'
    - '1025:1025'
