plugins:
  vision:
  inert:
  ./plugins/mailer:
    smtp:
      host: "{{ENV.SMTP_HOST}}"
      port: "{{ENV.SMTP_PORT}}"
      user: "{{ENV.SMTP_USER}}"
      pass: "{{ENV.SMTP_PASS}}"
views:
  engines:
    html: "handlebars"
  path: "{{CWD}}/emails"
  partialsPath: "{{CWD}}/partials"
  helpersPath: "{{CWD}}/helpers"
  isCached: true
