templatePath: "{{CWD}}/templates"
enableMetrics: "{{(ENV.MICRO_METRICS_HOST) ? true : false}}"
plugins:
  vision:
  inert:
  hapi-pagedata:
    _enabled: "{{(ENV.PAGEDATA_HOST) ? true : false}}"
    verbose: true
    host: "{{ENV.PAGEDATA_HOST}}"
    key: "{{ENV.PAGEDATA_KEY}}"
    hookEndpoint: '/pagedata/hook'
    cacheEndpoint: '/pagedata/cache'
    tag: "{{ENV.PAGEDATA_TAG}}"
  hapi-micro-metrics:
    _enabled: "{{enableMetrics}}"
    host: "{{ENV.MICRO_METRICS_HOST}}"
    verbose: true
  hapi-auto-handler:
    _priority: -1
  hapi-log-response:
  ./plugins/transport:
    _priority: -2
    smtp:
      host: "{{ENV.SMTP_HOST}}"
      port: "{{ENV.SMTP_PORT}}"
      user: "{{ENV.SMTP_USER}}"
      pass: "{{ENV.SMTP_PASS}}"
views:
  engines:
    html: "handlebars"
  path: "{{templatePath}}/emails"
  partialsPath: "{{templatePath}}/partials"
  helpersPath: "{{templatePath}}/helpers"
  isCached: true
