templatePath: "{{CWD}}/templates/emails"
plugins:
  vision:
  inert:
  ./plugins/mandrill:
    smtpPass: "{{ENV.SMTP_PASS}}"
emails:
  defaultDetails:
    from: 'no-reply@leanin.org'
    fromName: 'LeanIn.org'
views:
  engines:
    html: "handlebars"
  path: "{{templatePath}}"
  partialsPath: "{{CWD}}/templates/partials"
  helpersPath: "{{CWD}}/helpers"
  isCached: true
