templatePath: "{{CWD}}/templates"
plugins:
  vision:
  inert:
  hapi-pagedata:
    host: "{{ENV.PAGEDATA_HOST}}"
    key: "{{ENV.PAGEDATA_KEY}}"
  hapi-auto-handler:
    _priority: -1
  ./plugins/transport:
    _priority: -2
    smtp:
      host: "{{ENV.SMTP_HOST}}"
      port: "{{ENV.SMTP_PORT}}"
      user: "{{ENV.SMTP_USER}}"
      pass: "{{ENV.SMTP_PASS}}"
views:
  engines:
    html: "handlebars"
  path: "{{templatePath}}/emails"
  partialsPath: "{{templatePath}}/partials"
  helpersPath: "{{templatePath}}/helpers"
  isCached: true
