templatePath: "{{CWD}}/templates"
enableMetrics: "{{envVars.enableMetrics}}"
metricsHost: '{{ envVars.metricsHost }}'
plugins:
  vision:
  inert:
  hapi-route-loader:
    _dependencies:
      - 'hapi-api-key'
  hapi-api-key:
    _dependencies:
      - './plugins/loadHelpers'
      - './plugins/transport'
    strategy:
      name: 'apikey'
      mode: true
      apiKeys:
        '{{envVars.apiKey}}':
          name: 'micromail-api'
  hapi-pagedata:
    _enabled: "{{envExists('PAGEDATA_HOST')}}"
    host: "{{envVars.pagedata.host}}"
    key: "{{envVars.pagedata.key}}"
    status: "{{envVars.pagedata.status}}"
  hapi-micro-metrics:
    _enabled: "{{enableMetrics}}"
    host: "{{envVars.metricsHost}}"
    verbose: true
  ./plugins/loadHelpers:
    _dependencies:
      - 'vision'
    opens:
      enabled: true
      type: 'open'
    clicks:
      enabled: true
      type: 'email.click'
      tags: ''
    trackingUrl: '{{envVars.metricsHost}}'
  ./plugins/transport:
    _dependencies:
      - 'vision'
    smtp:
      host: "{{envVars.smtp.host}}"
      port: "{{envVars.smtp.port}}"
      user: "{{envVars.smtp.user}}"
      pass: "{{envVars.smtp.pass}}"
views:
  engines:
    njk: "vision-nunjucks"
  path: "{{templatePath}}/emails"
  defaultExtension: 'njk'
  compileMode: 'async'
