templatePath: "{{CWD}}/templates"
enableMetrics: "{{(ENV.MICRO_METRICS_HOST) ? true : false}}"
plugins:
  vision:
  inert:
  hapi-api-key:
    _priority: -1
    strategy:
      name: 'apikey'
      mode: true
      apiKeys:
        '{{ENV.MICROMAIL_API_KEY}}':
          name: 'micromail-api'
  hapi-pagedata:
    _enabled: "{{(ENV.PAGEDATA_HOST) ? true : false}}"
    verbose: true
    host: "{{ENV.PAGEDATA_HOST}}"
    key: "{{ENV.PAGEDATA_KEY}}"
    hookEndpoint: '/pagedata/hook'
    cacheEndpoint: '/pagedata/cache'
    tag: "{{ENV.PAGEDATA_TAG}}"
  hapi-micro-metrics:
    _enabled: "{{enableMetrics}}"
    host: "{{ENV.MICRO_METRICS_HOST}}"
    verbose: true
  hapi-auto-handler:
    _priority: -1
  hapi-log-response:
  ./plugins/loadHelpers:
    _priority: -2
    opens:
      enabled: true
      type: 'open'
    clicks:
      enabled: true
      type: 'email.click'
      tags: ''
    trackingUrl: '{{ENV.MICRO_METRICS_HOST}}'
  ./plugins/transport:
    _priority: -2
    smtp:
      host: "{{ENV.SMTP_HOST}}"
      port: "{{ENV.SMTP_PORT}}"
      user: "{{ENV.SMTP_USER}}"
      pass: "{{ENV.SMTP_PASS}}"
views:
  engines:
    njk: "vision-nunjucks"
  path: "{{templatePath}}/emails"
  defaultExtension: 'njk'
  compileMode: 'async'
