templatePath: "{{CWD}}/templates"
enableMetrics: "{{(ENV.MICRO_METRICS_HOST) ? true : false}}"
plugins:
  vision:
  inert:
  hapi-pagedata:
    _enabled: "{{enableMetrics }}"
    host: "{{ENV.PAGEDATA_HOST}}"
    key: "{{ENV.PAGEDATA_KEY}}"
  hapi-micro-metrics:
    _enabled: "{{(ENV.MICRO_METRICS_HOST) ? true : false }}"
    host: "{{ENV.MICRO_METRICS_HOST}}"
    verbose: "true"
  hapi-auto-handler:
    _priority: -1
  hapi-log-response:
  ./plugins/transport:
    _priority: -2
    smtp:
      host: "{{ENV.SMTP_HOST}}"
      port: "{{ENV.SMTP_PORT}}"
      user: "{{ENV.SMTP_USER}}"
      pass: "{{ENV.SMTP_PASS}}"
views:
  engines:
    html: "handlebars"
  path: "{{templatePath}}/emails"
  partialsPath: "{{templatePath}}/partials"
  helpersPath: "{{templatePath}}/helpers"
  isCached: true
