plugins:
  ./plugins/transport:
    _priority: -2
    smtp:
      host: "localhost"
      port: 8888
views:
  engines:
    html: "handlebars"
  path: "{{CWD}}/test/emails"
  partialsPath: "{{CWD}}/test/partials"
  helpersPath: "{{CWD}}/test/helpers"
  isCached: false
