port: 8080
plugins:
  hapi-api-key:
    _priority: -1
    strategy:
      name: 'apikey'
      mode: true
      apiKeys:
        '{{ENV.MICROMAIL_API_KEY}}':
          name: 'micromail-api'
  hapi-pagedata:
    _enabled: true
    host: 'http://localhost:3000'
    key: 'dummy'
  ./plugins/transport:
    _priority: -2
    smtp:
      host: "localhost"
      port: 8888
      user: 'user'
      pass: 'pass'
views:
  engines:
    html: "handlebars"
  path: "{{CWD}}/test/emails"
  partialsPath: "{{CWD}}/test/partials"
  helpersPath: "{{CWD}}/test/helpers"
  isCached: false
