port: 8080
enableMetrics: "true"
plugins:
  hapi-pagedata:
    _enabled: true
    host: 'http://localhost:3000'
    key: 'dummy'
    tag: 'tag'
  ./plugins/transport:
    _priority: -2
    smtp:
      host: "localhost"
      port: 8888
      user: 'user'
      pass: 'pass'
views:
  path: "{{CWD}}/test/emails"
  partialsPath: "{{CWD}}/test/partials"
  isCached: false
