plugins:
  ./plugins/transport:
    _priority: -2
    smtp:
      host: "localhost"
      port: 8888
  ./plugins/render:
    partialsPath: "{{CWD}}/test/templates/partials/"
    helpersPath: "{{CWD}}/test/templates/helpers/"
views:
  engines:
    html: "handlebars"
  path: "{{CWD}}/test/emails"
  isCached: false
