plugins:
  ./plugins/transport:
    _priority: -2
    smtp:
      host: "localhost"
      port: 8888
  ./plugins/render:
    path: "{{templatePath}}/test/emails"
    partialsPath: "test/templates/partials/"
    helpersPath: "test/templates/helpers/"
views:
  engines:
    html: "handlebars"
  path: "{{CWD}}/test/emails"
  isCached: false
